### PR TITLE
fix!: DBTP-1295 64 character limit cert

### PR DESCRIPTION
**Pull request by mramplin**
- Added Primary Domain Entry to CDN Module (mirroring ALB module)
- Moved certificate references from domain block (with 64-character limit) to subject_alternative_names (no 64-character limit)
- Reworked certificate validation to use subject_alternative_names for validation and create route53 validation domains.

### CODE REVIEW

**Review by ejayesh — COMMENTED** [review]
Although the terraform does not produce errors in a plan.  When running an apply it does raise errors around getting the R53 zones

**Review by ejayesh — COMMENTED** [review]
As this update now creates one shared certificate for all domains, rather than one certificate per domain.  This is a breaking change, when applying this terraform you will be deleting certificates and creating a single new one.  This new certificate gets attached to the CDN

**Comment by gabelton** [comment]
Is it possible for one of the unit tests to show a cert being created with a >64 character limit?

**Comment by ejayesh** [comment]
I think we can close this PR and refactor the change to maybe have the unit test check for a  64 char limit as @gabelton suggested

**Pull request closed without merging**
